# Generated by Django 6.0.4 on 2026-05-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={},
        ),
        migrations.RenameField(
            model_name='postmodel',
            old_name='long_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
