# Generated by Django 6.0.4 on 2026-05-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_bannermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.colormodel'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.sizemodel'),
        ),
    ]
