# Generated by Django 6.0.4 on 2026-05-14 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_categorymodel_name_en_categorymodel_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='colormodel',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='long_description_ru',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='short_description_ru',
        ),
    ]
