# Generated by Django 6.0.4 on 2026-05-23 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_cartmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='cart',
        ),
    ]
